# Generated by Django 3.0.3 on 2020-05-15 13:28

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='demand',
            name='file',
            field=models.FileField(blank=True, upload_to=website.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='demand',
            name='filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='height',
            field=models.FloatField(blank=True, default=1.5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='minimumDate',
            field=models.DateField(blank=True, default='2020-01-01', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='width',
            field=models.FloatField(blank=True, default=1.5, max_length=50),
            preserve_default=False,
        ),
    ]
