# Generated by Django 3.0.3 on 2020-05-15 14:13

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200515_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='email',
            field=models.CharField(default='olaxwilliam@gmail.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='file',
            field=models.FileField(upload_to=website.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='demand',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='height',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='minimumDate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='width',
            field=models.FloatField(max_length=50),
        ),
    ]
